spring:
  datasource:
    url: jdbc:postgresql://database-svc.default.svc.cluster.local:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: order-service
  profiles: qa

server:
  port: 8100

KAFKA_BOOSTRAPADDRESS: kafka-service.default.svc.cluster.local:9192
GROUPID: order

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${APIMANAGER_SVC_SERVICE_HOST}:${APIMANAGER_SVC_PORT_8000_TCP_PORT}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true
